version: '3.8'

services:
  web:
    build: .
    container_name: php56-web
    networks:
      - appnet
    volumes:
      - ./phpmyadmin-custom.conf:/etc/apache2/conf-enabled/phpmyadmin-custom.conf
      - ./my.cnf:/etc/mysql/my.cnf  # Mount your custom MySQL config
    environment:
      - MYSQL_ROOT_PASSWORD=Ma66217829
      - MYSQL_DATABASE=forum
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Ma66217829

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 3G
    ports:
      - "8083:80"  # Access phpMyAdmin at http://localhost:8083
    volumes:
      - ./phpmyadmin-custom.conf:/etc/apache2/conf-enabled/phpmyadmin-custom.conf
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ma66217829
      MYSQL_DATABASE: forum
      MYSQL_USER: root
      MYSQL_PASSWORD: Ma66217829
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf  # ← Ensure MySQL config is mounted
    networks:
      - appnet
    ports:
      - "3307:3306"  # Expose MySQL port to the host machine

volumes:
  db_data:

networks:
  appnet:
